apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - protocol: TCP
    port: 8180
    targetPort: 8180
  selector:
    service: reverseproxy