apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: MyEKSCluster
  region: us-east-1
  version: "1.21"
vpc:
  id: vpc-052d225bb4d221b44
  subnets:
    private:
      us-east-1a:
        id: subnet-0d63c9dfb27e50c9b
      us-east-1b:
        id: subnet-0100a9954914c8251
    public:
      us-east-1a:
        id: subnet-08bd815a7564981d1
      us-east-1b:
        id: subnet-0721ce513c127868d
managedNodeGroups:
- name: MyNodeGroup
  privateNetworking: true
  instanceType: m5.large
  desiredCapacity: 2
    